### ISSUE TITLE
Feature: Optimize session management

### ISSUE THREAD

**Issue by atimin** [reductstore/reduct-py#71]
### Current problem

We create a new session for each request, it is not efficient. We could use only one session for a client.

### Possible solution

We should not use `with` block for HTTP request and create a session inside the ReductClient class.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mounte** [comment]
+1 for this.
I work with a remote system with high latency, requests as currently implemented incur the latency penalty for every request.
By enabling session keep-alive things would probably be a lot faster.

I tried this:
In `__init__` in http.py
```python
self.connector = aiohttp.TCPConnector()
self.session = aiohttp.ClientSession(timeout = self.timeout, connector = self.connector)
```
In request() in http.py, remove the creation of connector and async with ClientSession and turned it into:
```python
        try:
            async with self.session.request(
                method,
                f"{self.url}{path.strip()}",
                headers=dict(self.headers, **extra_headers),
                expect100=expect100,
                **kwargs,
            ) as response:
                if response.ok:
                    yield response
                else:
                    if "x-reduct-error" in response.headers:
                        raise ReductError(
                            response.status,
                            response.headers["x-reduct-error"],
                        )
                    raise ReductError(response.status, "Unknown error")
        except ClientConnectorError:
            raise ReductError(
                599, f"Connection failed, server {self.url} cannot be reached"
            ) from None
```

I have not run any substantial tests to rule out any bad side-effects of this BUT what I did was to measure before and after.
The simplified test does some basic checking of buckets and fetching k records.

k=10
before: 15s
after: 7s

k=100
before: 100s
after: 51s

I did not tweak any of the keep-alive settings just the defaults coming with: TCPConnector and ClientSession.
I am getting data using `async for record in bucket.query("entry", start=..., stop=...)`

Another question, would it be possible to "batch load" records? I guess it would require backend changes to realize that there are ~k records to be sent, and batch them into m packages (with ~k/m records) of reasonable size and have client split up to individual records when iterating over it.
This should probably be an option since if you dont want to get hit by the added latency. But I see it very useful if you are fetching lots of data for some use-cases.

**Comment by atimin** [comment]
Hey @mounte, thank you for sharing this.

As you've already noticed, we're already working on batching records in one request: reductstore/reductstore#236. We started it in the C++ version, but have to start from scratch in the Rust implementation. The feature will be available in ReductStore v1.5 soon.

However, the session optimization is still relevant, and I see from your numbers it can improve a lot.

**Comment by atimin** [comment]
Hey again @mounte , I've tried your suggestions.. I didn't manage to make it work... could you make PR of your working changes? I'm not sure if the client was supposed to work without context manager.

P.S. The batching is ready in the development branches of `reduct-py` and `reductstore`. So if you're interested to try, you can take it from there. I'm preparing benchmarks.

**Comment by mounte** [comment]
nice @atimin I will have a look later this week and make a PR to test with. I need to read a bit on the aiohttp because I am not sure what I did is 100% correct and if it works in various cases...

**Comment by atimin** [comment]
@mounte I've found a way to reuse the HTTP session without breaking changes. You can use a context manager if you need better performance:

```python
    async with Client(url, api_token=api_token) as client:
        bucket = await client.create_bucket("bucket-1", exist_ok=True)
        await bucket.info()
```
